/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-04-21 04:08:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.calendar;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class calendar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/206-001/workspace/Spring-Web/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Project-Front/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1090214156000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1461211635102L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--[if IE 9 ]><html class=\"ie9\"><![endif]-->\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Material Admin</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Vendor CSS -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/animate-css/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/fullcalendar/fullcalendar.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/sweet-alert/sweet-alert.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/material-icons/material-design-iconic-font.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/socicon/socicon.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/noUiSlider/jquery.nouislider.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/farbtastic/farbtastic.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/summernote/summernote.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- CSS -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/css/app.min.1.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/css/app.min.2.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/css/bottom.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<section id=\"main\">\r\n");
      out.write("\t\t<section id=\"cal_content\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div id=\"calendar\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"contain\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-group\" id=\"accordion\">\r\n");
      out.write("\t\t\t\t\t    <div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t      <div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t        <h4 class=\"panel-title\" id=\"detailInfo\">\r\n");
      out.write("\t\t\t\t\t          <a data-toggle=\"collapse\" id = \"bottomDate\" data-parent=\"#accordion\" href=\"#collapse1\">Detail Information</a>\r\n");
      out.write("\t\t\t\t\t        </h4>\r\n");
      out.write("\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t      <div id=\"collapse1\" class=\"panel-collapse collapse in\">\r\n");
      out.write("\t\t\t\t\t        <div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p id=\"event\" style=\"width: 560px;\"></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p id=\"contents\" style=\"width: 560px; height: 30px;\"></p>\r\n");
      out.write("\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t     </div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- <button type=\"button\" class=\"btn btn-success\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"collapse\" data-target=\"#demo\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-collapse-down\"></span> Open\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"demo\" class=\"collapse\">\r\n");
      out.write("\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"eventbox\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"event\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input readonly type=\"text\" id=\"noticename\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 100%;\" /><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"contents\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input readonly type=\"text\" id=\"noticecontent\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 100%; height: 123px;\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- Add event -->\r\n");
      out.write("\t\t\t\t\t<div class=\"modal fade\" id=\"addNew-event\" data-backdrop=\"static\"\r\n");
      out.write("\t\t\t\t\t\tdata-keyboard=\"false\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"modal-title\">Add an Event</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form class=\"addEvent\" role=\"form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t                                    <div>\r\n");
      out.write("\t\t\t                                      <label class=\"input-group-add\" style=\"font-weight: bold; float:left;\">Date</label><br/>\r\n");
      out.write("\t\t\t                                      <div class=\"row\" style=\"float:left; padding-left:3px;\">\r\n");
      out.write("\t\t\t                                         <div class=\"input-group form-group\" >\r\n");
      out.write("\t\t\t                                              <span class=\"input-group-addon\"><i class=\"md md-event\"></i></span>\r\n");
      out.write("\t\t\t                                            <div class=\"dtp-container dropdown fg-line\">\r\n");
      out.write("\t\t\t                                               <input type='text' id=\"date\" class=\"form-control date-picker\" data-toggle=\"dropdown\" placeholder=\"Click here...\">\r\n");
      out.write("\t\t\t                                            </div>\r\n");
      out.write("\t\t\t                                         </div>\r\n");
      out.write("\t\t\t                                      </div>\r\n");
      out.write("\t\t\t                                    </div>\r\n");
      out.write("\t\t\t                                  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"eventName\">Event Name</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"addNotice\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"input-sm form-control\" id=\"eventName\" name=\"title\" placeholder=\"새로운 공지를 입력하세요.\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"eventName\">contents</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"addContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"input-sm form-control\" id=\"newCotents\" name=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"eventName\">Tag Color</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"event-tag\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span data-tag=\"bgm-teal\" class=\"bgm-teal selected\" name=\"className\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span data-tag=\"bgm-red\" class=\"bgm-red\" name=\"className\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-tag=\"bgm-pink\" class=\"bgm-pink\" name=\"className\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-tag=\"bgm-blue\" class=\"bgm-blue\" name=\"className\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-tag=\"bgm-lime\" class=\"bgm-lime\" name=\"className\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-tag=\"bgm-green\" class=\"bgm-green\" name=\"className\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-tag=\"bgm-cyan\" class=\"bgm-cyan\" name=\"className\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-tag=\"bgm-orange\" class=\"bgm-orange\" name=\"className\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-tag=\"bgm-purple\" class=\"bgm-purple\" name=\"className\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-tag=\"bgm-gray\" class=\"bgm-gray\" name=\"className\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-tag=\"bgm-black\" class=\"bgm-black\" name=\"className\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"getStart\" /> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"getEnd\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-link\" id=\"addEvent\">Add Event</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-link\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Modify event -->\r\n");
      out.write("\t\t\t\t\t<div class=\"modal fade\" id=\"modify-event\" data-backdrop=\"static\"\r\n");
      out.write("\t\t\t\t\t\tdata-keyboard=\"false\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"modal-title\">Modify an Event</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form class=\"addEvent\" role=\"form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"eventName\">Current Notice</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div id=\"current\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"input-sm form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"currentEventName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"eventName\">contents</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"modifyContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"input-sm form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"modifyContents\" name=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"eventName\">Tag Color</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"event-tag\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span data-tag=\"bgm-teal\" class=\"bgm-teal selected\" name=\"className\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span data-tag=\"bgm-red\" class=\"bgm-red\" name=\"className\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-tag=\"bgm-pink\" class=\"bgm-pink\" name=\"className\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-tag=\"bgm-blue\" class=\"bgm-blue\" name=\"className\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-tag=\"bgm-lime\" class=\"bgm-lime\" name=\"className\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-tag=\"bgm-green\" class=\"bgm-green\" name=\"className\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-tag=\"bgm-cyan\" class=\"bgm-cyan\" name=\"className\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-tag=\"bgm-orange\" class=\"bgm-orange\" name=\"className\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-tag=\"bgm-purple\" class=\"bgm-purple\" name=\"className\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-tag=\"bgm-gray\" class=\"bgm-gray\" name=\"className\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-tag=\"bgm-black\" class=\"bgm-black\" name=\"className\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"modifyGetStart\" /> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"hidden\" id=\"modifyGetEnd\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"calendarId\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-link\" id=\"modifyEvent\">Modify Notice</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-link\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- </div> -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Javascript Libraries -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/auto-size/jquery.autosize.min.js\"></script>\r\n");
      out.write(" \t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/fileinput/fileinput.min.js\"></script>\r\n");
      out.write(" \t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/input-mask/input-mask.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/farbtastic/farbtastic.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/summernote/summernote.min.js\"></script>\r\n");
      out.write(" \t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/noUiSlider/jquery.nouislider.all.min.js\"></script>\r\n");
      out.write(" \t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/chosen/chosen.jquery.min.js\"></script>\r\n");
      out.write(" \t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/bootstrap-select/bootstrap-select.min.js\"></script>\r\n");
      out.write(" \t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/moment/moment.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/nicescroll/jquery.nicescroll.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/fullcalendar/lib/moment.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/fullcalendar/fullcalendar.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/waves/waves.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/bootstrap-growl/bootstrap-growl.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/sweet-alert/sweet-alert.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/bootstrap-datetimepicker/bootstrap-datetimepicker.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("            $(document).ready(function() {\r\n");
      out.write("            \tvar today = new Date();\r\n");
      out.write("                var date = new Date();\r\n");
      out.write("                var start = new Date();\r\n");
      out.write("                var end = new Date();\r\n");
      out.write("                var d = date.getDate();\r\n");
      out.write("                var m = date.getMonth();\r\n");
      out.write("                var y = date.getFullYear();\r\n");
      out.write("\r\n");
      out.write("                var cId = $('#calendar'); //Change the name if you want. I'm also using thsi add button for more actions\r\n");
      out.write("\r\n");
      out.write("                var calNotices = new Array(); \r\n");
      out.write("    \t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t/* \t\tconsole.log(calNotices[0].title)\r\n");
      out.write("\t\t\t\tconsole.log(calNotices[0].description)\r\n");
      out.write("\t\t\t\tconsole.log(calNotices[0].start)\r\n");
      out.write("\t\t\t\tconsole.log(calNotices[0].end)\r\n");
      out.write("\t\t\t\tconsole.log(calNotices[0].className)\r\n");
      out.write("\t\t\t\tconsole.log(calNotices[0].id)\r\n");
      out.write("                 */\r\n");
      out.write("                //Generate the Calendar\r\n");
      out.write("                cId.fullCalendar({\r\n");
      out.write("                    header: {\r\n");
      out.write("                        right: '',\r\n");
      out.write("                        center: 'prev, title, next',\r\n");
      out.write("                        left: ''\r\n");
      out.write("                    },\r\n");
      out.write("                    \r\n");
      out.write("                     defaultView: 'month',\r\n");
      out.write("\r\n");
      out.write("                    dayRender: function (date, cell) {\r\n");
      out.write("                        \r\n");
      out.write("                    \t end.setDate(today.getDate()+7);\r\n");
      out.write("                         var cellDate = $(cell).data('date');\r\n");
      out.write("                      \r\n");
      out.write("                         var todayDate;\r\n");
      out.write("                         \r\n");
      out.write("                         if(m+1 < 10 ){\r\n");
      out.write("                         \tif(d < 10){\r\n");
      out.write("                         \t\ttodayDate = y+'-'+'0'+(m+1)+'-'+'0'+d;\r\n");
      out.write("                         \t}else{\r\n");
      out.write("                         \t\ttodayDate = y+'-'+'0'+(m+1)+'-'+d;\r\n");
      out.write("                         \t}\r\n");
      out.write("\r\n");
      out.write("                         }else {\r\n");
      out.write("                         \tif(d < 10){\r\n");
      out.write("                         \t\ttodayDate = y+'-'+(m+1)+'-'+'0'+d;\r\n");
      out.write("                         \t}else{\r\n");
      out.write("                         \t\ttodayDate = y+'-'+(m+1)+'-'+d;\r\n");
      out.write("                         \t}\r\n");
      out.write(" \t\t\t\t\t\t\t\r\n");
      out.write(" \t\t\t\t\t\t}\r\n");
      out.write("                         console.log(\"cellDate\"+cellDate);\r\n");
      out.write("                         console.log(\"todayDate\"+todayDate);\r\n");
      out.write("                         \r\n");
      out.write("                         if ( cellDate == todayDate) {\r\n");
      out.write("                             cell.css(\"background-color\", \"#a5cefc\");\r\n");
      out.write("                         }\r\n");
      out.write("                        \r\n");
      out.write("                       /*  var start = new Date();\r\n");
      out.write("                        start.setDate(today.getDate()+1);\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        while(start <= end){\r\n");
      out.write("                            \r\n");
      out.write("                          //alert(start + \"\\n\" + tomorrow);\r\n");
      out.write("                            if(start.getDate() == date.getDate()){\r\n");
      out.write("                                cell.css(\"background-color\", \"yellow\");\r\n");
      out.write("                            }\r\n");
      out.write("                    \r\n");
      out.write("                            \r\n");
      out.write("                           var newDate = start.setDate(start.getDate() + 1);\r\n");
      out.write("                           start = new Date(newDate);\r\n");
      out.write("                        }         */\r\n");
      out.write("                    },   \r\n");
      out.write("\r\n");
      out.write("                    fixedWeekCount: false,\r\n");
      out.write("                    contentHeight: 600,\r\n");
      out.write("                    eventLimit: true,\r\n");
      out.write("                    theme: true, //Do not remove this as it ruin the design\r\n");
      out.write("                    selectable: true,\r\n");
      out.write("                    selectHelper: true,\r\n");
      out.write("                    select: true,\r\n");
      out.write("                    editable: true,\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("                    //Add Events\r\n");
      out.write("                    events: calNotices,\r\n");
      out.write("                 //Cancel Event\r\n");
      out.write("                 eventRender: function(event, element) {\r\n");
      out.write("                        console.log(element);\r\n");
      out.write("                          var e = element\r\n");
      out.write("                                         .prepend(\"<span class='closeon'>&#10005;</span>\");\r\n");
      out.write("                          //element.find('.fc-title').append(\"<br/>\" + event.description);\r\n");
      out.write("                          \r\n");
      out.write("                          e.children('.closeon')\r\n");
      out.write("                             .attr('data-event-id', event._id) \r\n");
      out.write("                             .click( function() {\r\n");
      out.write("                                var id = $(this).attr('data-event-id');\r\n");
      out.write("                                alert(id);\r\n");
      out.write("                                if (id != '') {\r\n");
      out.write("                              \t  $.post(\"/delete\"\t\r\n");
      out.write("                                            , { \r\n");
      out.write("                                            \t\t\"id\" : id,\r\n");
      out.write("                                            \t}\r\n");
      out.write("                                            , function(d) {\r\n");
      out.write("                         \t\t\t\t\t\t\t\t var jsonData2 = {};\r\n");
      out.write("          \t                                  \ttry{\r\n");
      out.write("          \t              \t\t\t\t\t\t\tjsonData2 = JSON.parse(d);\r\n");
      out.write("          \t              \t\t\t\t\t\t\tif(jsonData2.deleteNotice) {\r\n");
      out.write("          \t              \t\t\t\t\t\t\talert(\"공지 관련 내용이 삭제되었습니다.\"); \r\n");
      out.write("          \t\t              \t\t\t\t\t\tlocation.href=\"/goMain\";\r\n");
      out.write("          \t              \t\t\t\t\t\t\t}\r\n");
      out.write("          \t              \t\t\t\t\t\t\telse {}\r\n");
      out.write("          \t              \t\t\t\t\t\t}\r\n");
      out.write("          \t              \t\t\t\t\t\tcatch(e) {\r\n");
      out.write("          \t              \t\t\t\t\t\t \talert(\"예상치 못한 에러가 발생했습니다. 관리자에게 문의하세요.\"); \r\n");
      out.write("          \t              \t\t\t\t\t\t}\r\n");
      out.write("                                            });\r\n");
      out.write("                                $('#calendar').fullCalendar('removeEvents',{\r\n");
      out.write("\t\t                            id: id\r\n");
      out.write("                        \t\t },true );\r\n");
      out.write("                                $('.closeon form')[0].reset();\r\n");
      out.write("                                $('.closeon').modal('hide');\r\n");
      out.write("                                \r\n");
      out.write("                            \t}\r\n");
      out.write("                             });\r\n");
      out.write("                        },\r\n");
      out.write("                        \r\n");
      out.write("                        //day click\r\n");
      out.write("                        dayClick: function(date, jsEvent, view) {\r\n");
      out.write("     \t\t\t\t        alert('Clicked on: ' + date.format());\r\n");
      out.write("     \t\t\t\t        \r\n");
      out.write("     \t\t\t\t    \t$.post(\"/getDayChat\"\t\r\n");
      out.write("     \t\t                          , { \r\n");
      out.write("     \t\t              \t\t\t\t\tselectDay : date.format()\r\n");
      out.write("     \t\t                          \t}\r\n");
      out.write("     \t\t                          , function(data) {\r\n");
      out.write("     \t\t       \t\t\t\t\t\t\t\t var jsonData3 = {};\r\n");
      out.write("     \t\t                             \ttry{\r\n");
      out.write("     \t\t         \t\t\t\t\t\t\tjsonData3 = JSON.parse(data);\r\n");
      out.write("     \t\t         \t\t\t\t\t\t\tif(jsonData3.success) {\r\n");
      out.write("     \t\t          \t\t\t\t\t\t\t\tlocation.href=\"/showDayChat?selectDay=\"+date.format();\r\n");
      out.write("     \t\t         \t\t\t\t\t\t\t}\r\n");
      out.write("     \t\t         \t\t\t\t\t\t\telse {\r\n");
      out.write("     \t\t         \t\t\t\t\t \t\t\talert(\"해당 날짜에 해당하는 대화가 없습니다.\"); \r\n");
      out.write("     \t\t          \t\t\t\t\t\t\t\tlocation.href=\"/goMain\";\r\n");
      out.write("     \t\t         \t\t\t\t\t\t\t}\r\n");
      out.write("     \t\t         \t\t\t\t\t\t}\r\n");
      out.write("     \t\t         \t\t\t\t\t\tcatch(e) {\r\n");
      out.write("     \t\t         \t\t\t\t\t\t \talert(\"예상치 못한 에러가 발생했습니다. 관리자에게 문의하세요.\"); \r\n");
      out.write("     \t\t         \t\t\t\t\t\t}\r\n");
      out.write("     \t\t                          });\r\n");
      out.write("     \t                        \r\n");
      out.write("        \t\t\t\t\t}, \r\n");
      out.write("                        \r\n");
      out.write("                   //event contents\r\n");
      out.write("                    /*  eventRender: function(event, element) {\r\n");
      out.write("\t\t\t\t\t        element.qtip({\r\n");
      out.write("\t\t\t\t\t            content: event.description\r\n");
      out.write("\t\t\t\t\t        });\r\n");
      out.write("\t\t\t\t\t    }, */\r\n");
      out.write("                     //Highlight Event\r\n");
      out.write("                         /*  eventRender: function(event, element, view) {\r\n");
      out.write("                            // event._id gets auto-populated, either event.id or auto-generated value\r\n");
      out.write("                            element.attr('data-id', event._id);\r\n");
      out.write("                            toggleClass(event._id);\r\n");
      out.write("                          }, \r\n");
      out.write("                          eventClick: function(event, jsEvent, view) {\r\n");
      out.write("                            toggleClass(event._id);\r\n");
      out.write("                          }, */\r\n");
      out.write("\r\n");
      out.write("                    //day click\r\n");
      out.write("                   /*  dayClick: function(date, jsEvent, view) {\r\n");
      out.write("\t\t\t\t        alert('Clicked on: ' + date.format());\r\n");
      out.write("   \t\t\t\t\t}, */\r\n");
      out.write("                          \r\n");
      out.write("                    //On Day Select\r\n");
      out.write("                  select: function(start, end, allDay) {\r\n");
      out.write("                        //$('#addNew-event').modal('show');\r\n");
      out.write("                        $('#addNew-event input:text').val('');\r\n");
      out.write("                        $('#addContent input:text').val('');\r\n");
      out.write("                        $('#current input:text').val('');\r\n");
      out.write("                        $('#getStart').val(start);\r\n");
      out.write("                        $('#getEnd').val(end);\r\n");
      out.write("                        var moment = $('.callender_area').fullCalendar('stickySource.title');\r\n");
      out.write("                    },\r\n");
      out.write("                    eventClick: function(calEvent, jsEvent, view) {\r\n");
      out.write("                    \t// $('#modify-event').modal('show');\r\n");
      out.write("                    \t$('#addNotice input:text').val('');\r\n");
      out.write("                        $('#current input:text').val(calEvent.title);\r\n");
      out.write("                        $('#modifyContent input:text').val(calEvent.description);\r\n");
      out.write("                        $('#event').html('◎ 카톡 공지:   ' + calEvent.title);\r\n");
      out.write("                        $('#contents').html('◎ 카톡 내용:   ' + calEvent.description);\r\n");
      out.write("                        $('#modifyGetStart').val(calEvent.start);\r\n");
      out.write("                        $('#modifyGetEnd').val(calEvent.end);\r\n");
      out.write("                        $('#bottomDate').html('Detail Infomation: ' + calEvent.start.format(('MM월 DD일 h:mm A')));\r\n");
      out.write("                        $('#calendarId').val(calEvent.id);\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                /*  var today ='<ul class=\"actions actions-alt\" id=\"todays\">' +\r\n");
      out.write("                 \t\t\t'</ul>'; */\r\n");
      out.write("\t                      \r\n");
      out.write("              //Hightlight Event\r\n");
      out.write("               function toggleClass(id) {\r\n");
      out.write("                          /* Find all segments for the specific event and toggle a class */\r\n");
      out.write("                          var $event = $('a.fc-event[data-id=\"' + id + '\"]');\r\n");
      out.write("                          $('a.my-highlight').each(function() {\r\n");
      out.write("                            $(this).toggleClass('my-highlight');\r\n");
      out.write("                          });\r\n");
      out.write("                          $.each($event, function() {\r\n");
      out.write("                            $(this).toggleClass('my-highlight');\r\n");
      out.write("                          });\r\n");
      out.write("                        }\r\n");
      out.write("              \r\n");
      out.write("                //Event Tag Selector\r\n");
      out.write("               (function(){\r\n");
      out.write("                    $('body').on('click', '.event-tag > span', function(){\r\n");
      out.write("                        $('.event-tag > span').removeClass('selected');\r\n");
      out.write("                        $(this).addClass('selected');\r\n");
      out.write("                    });\r\n");
      out.write("                })();\r\n");
      out.write("                \r\n");
      out.write("                //Add new Event\r\n");
      out.write("                $('body').on('click', '#addEvent', function(){\r\n");
      out.write("                    var newNoticeName = $('#eventName').val();\r\n");
      out.write("                    var description = $('#newCotents').val();\r\n");
      out.write("                    var tagColor = $('.event-tag > span.selected').attr('data-tag');\r\n");
      out.write("                   /*  var startDate = $('#getStart').val();\r\n");
      out.write("                    var endDate = $('#getEnd').val(); */\r\n");
      out.write("                    var startDate = $('#date').val();\r\n");
      out.write("                    var endDate = $('#date').val();\r\n");
      out.write("                    alert(startDate);\r\n");
      out.write("                    \r\n");
      out.write("                    if (newNoticeName != '') {\r\n");
      out.write("                    \t  $.post(\"/calendar\"\t\r\n");
      out.write("                                  , { \r\n");
      out.write("                                  \t\t\"title\" : newNoticeName,\r\n");
      out.write("                              \t \t\t\"description\" : description,\r\n");
      out.write("                                  \t\t\"className\" : tagColor,\r\n");
      out.write("                                  \t\t\"getStart\" : startDate,\r\n");
      out.write("                                  \t\t\"getEnd\" : endDate,\r\n");
      out.write("                                  \t}\r\n");
      out.write("                                  , function(data) {\r\n");
      out.write("               \t\t\t\t\t\t\t\t var jsonData3 = {};\r\n");
      out.write("\t                                  \ttry{\r\n");
      out.write("\t              \t\t\t\t\t\t\tjsonData3 = JSON.parse(data);\r\n");
      out.write("\t              \t\t\t\t\t\t\tif(jsonData3.updateNotice) {\r\n");
      out.write("\t              \t\t\t\t\t\t\t\r\n");
      out.write("\t              \t\t\t\t\t\t\talert(\"정보가 입력되었습니다.\");\r\n");
      out.write("\t\t              \t\t\t\t\t\tlocation.href=\"/goMain\";\r\n");
      out.write("\t              \t\t\t\t\t\t\t}\r\n");
      out.write("\t              \t\t\t\t\t\t\telse {}\r\n");
      out.write("\t              \t\t\t\t\t\t}\r\n");
      out.write("\t              \t\t\t\t\t\tcatch(e) {\r\n");
      out.write("\t              \t\t\t\t\t\t\talert(\"예상치 못한 에러가 발생했습니다. 관리자에게 문의하세요.\");\r\n");
      out.write("\t              \t\t\t\t\t\t}\r\n");
      out.write("                                  });\r\n");
      out.write("                        //Render Event\r\n");
      out.write("                        $('#calendar').fullCalendar('renderEvent'\r\n");
      out.write("                        \t\t,{\r\n");
      out.write("\t\t                            title: newNoticeName,\r\n");
      out.write("\t\t                            description: description,\r\n");
      out.write("\t\t                            start: $('#getStart').val(),\r\n");
      out.write("\t\t                            end:  $('#getEnd').val(),\r\n");
      out.write("\t\t                            allDay: true,\r\n");
      out.write("\t\t                            className: tagColor\r\n");
      out.write("                        \t\t },true ); //Stick the event\r\n");
      out.write("                        $('#addNew-event form')[0].reset();\r\n");
      out.write("                        $('#addNew-event').modal('hide');\r\n");
      out.write("                        \r\n");
      out.write("                    }\r\n");
      out.write("                    else {\r\n");
      out.write("                        $('#eventName').closest('.form-group').addClass('has-error');\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                //today click\r\n");
      out.write("                    $('#my-today-button').click(function() {\r\n");
      out.write("                    $('#calendar').fullCalendar('today');\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                // Modify an Event\r\n");
      out.write("                $('body').attr('calendarId', event._id).on('click', '#modifyEvent', function(){\r\n");
      out.write("                \t\r\n");
      out.write("                    var modifNoticeName = $('#currentEventName').val();\r\n");
      out.write("                    var description = $('#modifyContents').val();\r\n");
      out.write("                    var tagColor = $('.event-tag > span.selected').attr('data-tag');\r\n");
      out.write("                    var startDate = $('#modifyGetStart').val();\r\n");
      out.write("                    var endDate = $('#modifyGetEnd').val();\r\n");
      out.write("                    var calendarId =  $('#calendarId').val();\r\n");
      out.write("                    //alert(modifNoticeName);\r\n");
      out.write("                    //alert(description);\r\n");
      out.write("                    //alert(tagColor);\r\n");
      out.write("                    //alert(startDate);\r\n");
      out.write("                    //alert(endDate);\r\n");
      out.write("                    //alert(calendarId);\r\n");
      out.write("                    \r\n");
      out.write("                    if (modifNoticeName != '') {\r\n");
      out.write("                    \t");
//TODO 이벤트 정보를 AJAX로 보내서 DB에 저장해야함
      out.write("\r\n");
      out.write("                    \t $.post(\"/modify\"\r\n");
      out.write("                                 , { \r\n");
      out.write("                                 \t\t//\"title\" : newNoticeName,\r\n");
      out.write("                                 \t\t\r\n");
      out.write("                                 \t\t\"modifyTitle\" : modifNoticeName,\r\n");
      out.write("                             \t \t\t\"description\" : description,\r\n");
      out.write("                                 \t\t\"className\" : tagColor,\r\n");
      out.write("                                 \t\t\"getStart\" : startDate,\r\n");
      out.write("                                 \t\t\"getEnd\" : endDate,\r\n");
      out.write("                                 \t\t\"calendarId\" : calendarId,\r\n");
      out.write("                                 \t}\r\n");
      out.write("                                 , function(info) {\r\n");
      out.write("              \t\t\t\t\t\t\t\t var jsonData1 = {};\r\n");
      out.write("\t                                  \ttry{\r\n");
      out.write("\t              \t\t\t\t\t\t\tjsonData1 = JSON.parse(info);\r\n");
      out.write("\t              \t\t\t\t\t\t\tif(jsonData1.modifyNotice) {\r\n");
      out.write("\t              \t\t\t\t\t\t\t\t\r\n");
      out.write("\t              \t\t\t\t\t\t\talert(\"정보가 수정되었습니다.\");\r\n");
      out.write("\t\t              \t\t\t\t\t\tlocation.href=\"/goMain\";\r\n");
      out.write("\t              \t\t\t\t\t\t\t}\r\n");
      out.write("\t              \t\t\t\t\t\t\telse {}\r\n");
      out.write("\t              \t\t\t\t\t\t}\r\n");
      out.write("\t              \t\t\t\t\t\tcatch(e) {\r\n");
      out.write("\t              \t\t\t\t\t\t\talert(\"예상치 못한 에러가 발생했습니다. 관리자에게 문의하세요.\");\r\n");
      out.write("\t              \t\t\t\t\t\t}\r\n");
      out.write("                                 });\r\n");
      out.write("                    \t//Render Event\r\n");
      out.write("                        $('#calendar').fullCalendar('renderEvent'\r\n");
      out.write("                        \t\t,{\r\n");
      out.write("\t\t                            //title: newNoticeName,\r\n");
      out.write("\t\t                            title: modifNoticeName,\r\n");
      out.write("\t\t                            description: description,\r\n");
      out.write("\t\t                            start: $('#modifyGetStart').val(),\r\n");
      out.write("\t\t                            end:  $('#modifyGetEnd').val(),\r\n");
      out.write("\t\t                            allDay: true,\r\n");
      out.write("\t\t                            className: tagColor,\r\n");
      out.write("\t\t                            id: calendarId\r\n");
      out.write("                        \t\t }, true ); //Stick the event\r\n");
      out.write("                        \r\n");
      out.write("                        $('#modify-event form')[0].reset();\r\n");
      out.write("                        $('#modify-event').modal('hide');\r\n");
      out.write("                        \r\n");
      out.write("                    }\r\n");
      out.write("                    else {\r\n");
      out.write("                        $('#currentEventName').closest('.form-group').addClass('has-error');\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                //confirm cencel\r\n");
      out.write("                /*  $('body').on('click', '#modifyEvent', function(){\r\n");
      out.write("                    var eventName = $('#modifyEventName').val();\r\n");
      out.write("                    var tagColor = $('.event-tag > span.selected').attr('data-tag');\r\n");
      out.write("                        \r\n");
      out.write("                    $('#modifyEventName').closest('.form-group').addClass('has-error');\r\n");
      out.write("                }); */\r\n");
      out.write("                //Calendar views\r\n");
      out.write("                $('body').on('click', '#fc-actions [data-view]', function(e){\r\n");
      out.write("                    e.preventDefault();\r\n");
      out.write("                    var dataView = $(this).attr('data-view');\r\n");
      out.write("                    \r\n");
      out.write("                    $('#fc-actions li').removeClass('active');\r\n");
      out.write("                    $(this).parent().addClass('active');\r\n");
      out.write("                    cId.fullCalendar('changeView', dataView);\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                /* $('body').on('click', '#todays', function(e){\r\n");
      out.write("                    e.preventDefault();\r\n");
      out.write("                   \r\n");
      out.write("                }); */\r\n");
      out.write("                \r\n");
      out.write("                /* $(\"body\").on(\"click\", \".fc-title\", function() {\r\n");
      out.write("        \t\t\talert($(this).html());\r\n");
      out.write("        \t\t}); */\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t\t$('body').on('click', '#addButton', function(e){\r\n");
      out.write("\r\n");
      out.write("        \t\t\tvar button = $(\"#addButton\");\r\n");
      out.write("        \t\t\tbutton.attr(\"data-target\",\"#addNew-event\");\r\n");
      out.write("                });\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t\t$('body').on('click', '#editButton', function(e){\r\n");
      out.write("\r\n");
      out.write("        \t\t\t//var currentNotice = $(\"#currentEventName\").val();\r\n");
      out.write("        \t\t\tvar button = $(\"#editButton\");\r\n");
      out.write("        \t\t\t//console.log(currentNotice);\r\n");
      out.write("        \t\t\t\tbutton.attr(\"data-target\",\"#modify-event\");\r\n");
      out.write("        \t\t\t/* if (currentNotice != \"\"  ) { \r\n");
      out.write("        \t\t\t}\r\n");
      out.write("        \t\t\telse {\r\n");
      out.write("    \t            \tbutton.attr(\"data-target\",\"#addNew-event\");\r\n");
      out.write("        \t\t\t}  */\r\n");
      out.write("                });\r\n");
      out.write("        \t\t\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/view/calendar/calendar.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("root");
    // /WEB-INF/view/calendar/calendar.jsp(4,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/view/calendar/calendar.jsp(233,7) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ calNotice }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/view/calendar/calendar.jsp(233,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("notice");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\tvar calNotice = {};\t\r\n");
          out.write("\t\t\t\t\tcalNotice.id = \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.calendarId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("\t\t\t\t\tcalNotice.title = \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\";\r\n");
          out.write("\t\t\t\t\tcalNotice.description = \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\";\r\n");
          out.write("\t\t\t\t\tcalNotice.start = \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.startDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\";\r\n");
          out.write("\t\t\t\t\tcalNotice.end = \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.endDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\";\r\n");
          out.write("\t\t\t\t\tcalNotice.className = \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.className}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\";\r\n");
          out.write("\t\t\t\t\tcalNotices.push(calNotice);\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
