/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-04-21 04:08:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_005fview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/206-001/workspace/Spring-Web/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Project-Front/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1090214156000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1461211635102L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<ul class=\"tab-nav tn-justified\" style=\"color: #323e4a; background-color: #edecec; \">\r\n");
      out.write("    <li class=\"waves-effect\"><a href=\"/teamInfo\" style=\"color: #323e4a;\">Team Information</a></li>\r\n");
      out.write("    <li class=\"waves-effect\"><a href=\"/propertyMember\" style=\"color: #323e4a;\">CHAT ANALYSIS</a></li>\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!-- <div role=\"tabpanel\">\r\n");
      out.write("    <ul class=\"tab-nav\" role=\"tablist\" data-tab-color=\"red\">\r\n");
      out.write("        <li class=\"active\"><a href=\"#home11\" aria-controls=\"home11\" role=\"tab\" data-toggle=\"tab\">Team Information</a></li>\r\n");
      out.write("        <li><a href=\"#profile11\" aria-controls=\"profile11\" role=\"tab\" data-toggle=\"tab\">Chat By Calendar</a></li>\r\n");
      out.write("        <li><a href=\"#messages11\" aria-controls=\"messages11\" role=\"tab\" data-toggle=\"tab\">Chat By Member</a></li>\r\n");
      out.write("        <li><a href=\"#settings11\" aria-controls=\"settings11\" role=\"tab\" data-toggle=\"tab\">Property By Member</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("\t<div class=\"tab-content\">\r\n");
      out.write("\t    <div role=\"tabpanel\" class=\"tab-pane active\" id=\"home11\">\r\n");
      out.write("\t          <div class=\"block-header\">\r\n");
      out.write("\t              <h2>Buttons</h2>\r\n");
      out.write("\t          \r\n");
      out.write("\t              <ul class=\"actions\">\r\n");
      out.write("\t                  <li>\r\n");
      out.write("\t                      <a href=\"\">\r\n");
      out.write("\t                          <i class=\"md md-trending-up\"></i>\r\n");
      out.write("\t                      </a>\r\n");
      out.write("\t                  </li>\r\n");
      out.write("\t                  <li>\r\n");
      out.write("\t                      <a href=\"\">\r\n");
      out.write("\t                          <i class=\"md md-done-all\"></i>\r\n");
      out.write("\t                      </a>\r\n");
      out.write("\t                  </li>\r\n");
      out.write("\t                  <li class=\"dropdown\">\r\n");
      out.write("\t                      <a href=\"\" data-toggle=\"dropdown\">\r\n");
      out.write("\t                          <i class=\"md md-more-vert\"></i>\r\n");
      out.write("\t                      </a>\r\n");
      out.write("\t          \r\n");
      out.write("\t                      <ul class=\"dropdown-menu dropdown-menu-right\">\r\n");
      out.write("\t                          <li>\r\n");
      out.write("\t                              <a href=\"\">Refresh</a>\r\n");
      out.write("\t                          </li>\r\n");
      out.write("\t                          <li>\r\n");
      out.write("\t                              <a href=\"\">Manage Widgets</a>\r\n");
      out.write("\t                          </li>\r\n");
      out.write("\t                          <li>\r\n");
      out.write("\t                              <a href=\"\">Widgets Settings</a>\r\n");
      out.write("\t                          </li>\r\n");
      out.write("\t                      </ul>\r\n");
      out.write("\t                  </li>\r\n");
      out.write("\t              </ul>\r\n");
      out.write("\t          \r\n");
      out.write("\t          </div>\r\n");
      out.write("\t      \r\n");
      out.write("\t          <div class=\"card\">\r\n");
      out.write("\t              <div class=\"card-header\">\r\n");
      out.write("\t                  <h2>Basic Examples <small>Use any of the available button classes to quickly create a styled button.</small></h2>\r\n");
      out.write("\t          \r\n");
      out.write("\t                  <ul class=\"actions\">\r\n");
      out.write("\t                      <li class=\"dropdown action-show\">\r\n");
      out.write("\t                          <a href=\"\" data-toggle=\"dropdown\">\r\n");
      out.write("\t                              <i class=\"md md-more-vert\"></i>\r\n");
      out.write("\t                          </a>\r\n");
      out.write("\t          \r\n");
      out.write("\t                          <div class=\"dropdown-menu pull-right\">\r\n");
      out.write("\t                              <p class=\"p-20\">\r\n");
      out.write("\t                                  You can put anything here\r\n");
      out.write("\t                              </p>\r\n");
      out.write("\t                          </div>\r\n");
      out.write("\t                      </li>\r\n");
      out.write("\t                  </ul>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t          \r\n");
      out.write("\t              <div class=\"card-body card-padding\">\r\n");
      out.write("\t                  <p class=\"f-500 c-black m-b-20\">Bootstrap Color Schemes</p>\r\n");
      out.write("\t                  \r\n");
      out.write("\t                  <div class=\"btn-demo\">\r\n");
      out.write("\t                      <button class=\"btn btn-default\">Default</button>\r\n");
      out.write("\t                      <button class=\"btn btn-info\">Info</button>\r\n");
      out.write("\t                      <button class=\"btn btn-primary\">Primary</button>\r\n");
      out.write("\t                      <button class=\"btn btn-success\">Success</button>\r\n");
      out.write("\t                      <button class=\"btn btn-warning\">Warning</button>\r\n");
      out.write("\t                      <button class=\"btn btn-danger\">Danger</button>\r\n");
      out.write("\t                  </div>\r\n");
      out.write("\t                  \r\n");
      out.write("\t                  <br/>\r\n");
      out.write("\t                  <br/>\r\n");
      out.write("\t                  \r\n");
      out.write("\t                  <p class=\"f-500 c-black m-b-20\">Optional Material Design Colors</p>\r\n");
      out.write("\t                  \r\n");
      out.write("\t                  <div class=\"btn-colors btn-demo\"> Optional container for demo porpose only\r\n");
      out.write("\t                          <button class=\"btn bgm-cyan\">Cyan</button>\r\n");
      out.write("\t                          <button class=\"btn bgm-teal\">Teal</button>\r\n");
      out.write("\t                          <button class=\"btn bgm-amber\">Amber</button>\r\n");
      out.write("\t                          <button class=\"btn bgm-orange\">Orange</button>\r\n");
      out.write("\t                          <button class=\"btn bgm-deeporange\">Deep Orange</button>\r\n");
      out.write("\t                          <button class=\"btn bgm-red\">Red</button>\r\n");
      out.write("\t                          <button class=\"btn bgm-pink\">Pink</button>\r\n");
      out.write("\t                          <button class=\"btn bgm-lightblue\">Light Blue</button>\r\n");
      out.write("\t                          <button class=\"btn bgm-blue\">Blue</button>\r\n");
      out.write("\t                          <button class=\"btn bgm-indigo\">Indigo</button>\r\n");
      out.write("\t                          <button class=\"btn bgm-lime\">Lime</button>\r\n");
      out.write("\t                          <button class=\"btn bgm-lightgreen\">Light Green</button>\r\n");
      out.write("\t                          <button class=\"btn bgm-green\">Green</button>\r\n");
      out.write("\t                          <button class=\"btn bgm-purple\">Purple</button>\r\n");
      out.write("\t                          <button class=\"btn bgm-deeppurple\">Deep Purple</button>\r\n");
      out.write("\t                          <button class=\"btn bgm-gray\">Gray</button>\r\n");
      out.write("\t                          <button class=\"btn bgm-bluegray\">Blue Gray</button>\r\n");
      out.write("\t                          <button class=\"btn bgm-black\">Black</button>\r\n");
      out.write("\t                      </div>\r\n");
      out.write("\t                      \r\n");
      out.write("\t                      <br/>\r\n");
      out.write("\t                      <br/>\r\n");
      out.write("\t                      \r\n");
      out.write("\t                      <p class=\"f-500 c-black m-b-5\">Button Sizes</p>\r\n");
      out.write("\t                      <small>Fancy larger or smaller buttons? Add the button sizing classes.</small>\r\n");
      out.write("\t                      \r\n");
      out.write("\t                      <br/>\r\n");
      out.write("\t                      <br/>\r\n");
      out.write("\t                      \r\n");
      out.write("\t                      <div class=\"btn-demo\">\r\n");
      out.write("\t                          <button class=\"btn btn-primary btn-lg\">Large</button>\r\n");
      out.write("\t                          <button class=\"btn btn-primary\">Default</button>\r\n");
      out.write("\t                          <button class=\"btn btn-primary btn-sm\">Small</button>\r\n");
      out.write("\t                          <button class=\"btn btn-primary btn-xs\">Extra Small</button>\r\n");
      out.write("\t                      </div>\r\n");
      out.write("\t\r\n");
      out.write("\t                      <br/>\r\n");
      out.write("\t                      <br/>\r\n");
      out.write("\t                      \r\n");
      out.write("\t                      <p class=\"f-500 c-black m-b-20\">Disable Stat</p>\r\n");
      out.write("\t                      \r\n");
      out.write("\t                      <div class=\"btn-demo\">\r\n");
      out.write("\t                          <button class=\"btn btn-default\" disabled=\"disabled\">Default</button>\r\n");
      out.write("\t                          <button class=\"btn btn-info\" disabled=\"disabled\">Info</button>\r\n");
      out.write("\t                          <button class=\"btn btn-primary\" disabled=\"disabled\">Primary</button>\r\n");
      out.write("\t                          <button class=\"btn btn-success\" disabled=\"disabled\">Success</button>\r\n");
      out.write("\t                          <button class=\"btn btn-warning\" disabled=\"disabled\">Warning</button>\r\n");
      out.write("\t                          <button class=\"btn btn-danger\" disabled=\"disabled\">Danger</button>\r\n");
      out.write("\t                      </div>\r\n");
      out.write("\t                  </div>\r\n");
      out.write("\t              </div>\r\n");
      out.write("      \t\t</div>\r\n");
      out.write("      <div role=\"tabpanel\" class=\"tab-pane\" id=\"profile11\">\r\n");
      out.write("      2ë²\r\n");
      out.write("      </div>\r\n");
      out.write("      <div role=\"tabpanel\" class=\"tab-pane\" id=\"messages11\">\r\n");
      out.write("      3ë²\r\n");
      out.write("      </div>\r\n");
      out.write("      <div role=\"tabpanel\" class=\"tab-pane\" id=\"settings11\">\r\n");
      out.write("      4ë²\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div> -->\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/view/view/main_view.jsp(17,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("leaderEmail");
    // /WEB-INF/view/view/main_view.jsp(17,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope._TEAM_.leaderEmail }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f1.setParent(null);
    // /WEB-INF/view/view/main_view.jsp(18,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setVar("Useremail");
    // /WEB-INF/view/view/main_view.jsp(18,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope._MEMBER_.email }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
    if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/view/view/main_view.jsp(23,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ leaderEmail eq Useremail }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t<li class=\"waves-effect\"><a href=\"/goManageTeam\" style=\"color: #323e4a;\">TEAM SETTING</a></li>\r\n");
        out.write("\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }
}
