/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-04-21 04:07:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ktds.pingpong.member.vo.MemberVO;
import com.ktds.pingpong.history.vo.OperationHistoryVO;
import com.ktds.pingpong.history.biz.OperationHistoryBiz;
import com.ktds.pingpong.history.vo.ActionCode;
import com.ktds.pingpong.history.vo.Description;
import com.ktds.pingpong.history.vo.BuildDescription;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ktds.pingpong.history.vo.OperationHistoryVO");
    _jspx_imports_classes.add("com.ktds.pingpong.history.vo.Description");
    _jspx_imports_classes.add("com.ktds.pingpong.history.biz.OperationHistoryBiz");
    _jspx_imports_classes.add("com.ktds.pingpong.history.vo.ActionCode");
    _jspx_imports_classes.add("com.ktds.pingpong.member.vo.MemberVO");
    _jspx_imports_classes.add("com.ktds.pingpong.history.vo.BuildDescription");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");

	MemberVO member = (MemberVO) session.getAttribute("_MEMBER_");
	if ( member != null ){
		OperationHistoryVO historyVO = new OperationHistoryVO();
		historyVO.setIp(request.getRemoteHost());
		historyVO.setEmail(member.getEmail());
		historyVO.setUrl(request.getRequestURI());
		historyVO.setActionCode(ActionCode.LOGIN);
		historyVO.setDescription(BuildDescription
				.get(Description.ALREADY_LOGIN, member.getEmail())
				);
		
		OperationHistoryBiz biz = new OperationHistoryBiz();
		biz.addHistory(historyVO);
		
		response.sendRedirect("/goMain");
		return;
	}

	
	OperationHistoryVO historyVO = new OperationHistoryVO();
	historyVO.setIp(request.getRemoteHost());
	historyVO.setEmail("");
	historyVO.setUrl(request.getRequestURI());
	historyVO.setActionCode(ActionCode.LOGIN);
	historyVO.setDescription(BuildDescription
			.get(Description.VISIT_LOGIN_PAGE, request.getRemoteHost())
			);
	
	OperationHistoryBiz biz = new OperationHistoryBiz();
	biz.addHistory(historyVO);

      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>PingPong Chat</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resource/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resource/css/bootstrap-theme.min.css\">\r\n");
      out.write("<link href=\"resource/css/cover.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".carousel{\r\n");
      out.write("    background: #2f4357;\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write(".carousel .item img{\r\n");
      out.write("    margin: 0 auto; /* Align slide image horizontally center */\r\n");
      out.write("}\r\n");
      out.write(".bs-example{\r\n");
      out.write("\tmargin: 20px;\r\n");
      out.write("}\r\n");
      out.write("h2 { \r\n");
      out.write("\tcolor: #F44336;\r\n");
      out.write("}\r\n");
      out.write("html {\r\n");
      out.write("  font-family: sans-serif;\r\n");
      out.write("  -ms-text-size-adjust: 100%;\r\n");
      out.write("  -webkit-text-size-adjust: 100%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <div class=\"site-wrapper\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"site-wrapper-inner\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"cover-container\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"masthead clearfix\">\r\n");
      out.write("            <div class=\"inner\">\r\n");
      out.write("              <h2 class=\"masthead-brand\" color=\"#FFFFFF\">PINGPONG CHAT</h2>\r\n");
      out.write("              <nav>\r\n");
      out.write("                <ul class=\"nav masthead-nav\">\r\n");
      out.write("                  <li><a href=\"/goLogin\" style=\"font-size : 17x;\">Login</a></li>\r\n");
      out.write("                  <li><a href=\"/goSignup\" style=\"font-size : 17px;\">Sign Up</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"inner cover\">\r\n");
      out.write("            \r\n");
      out.write("\t\t\t\t<div class=\"bs-example\">\r\n");
      out.write("\t\t\t\t    <div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("\t\t\t\t        <!-- Carousel indicators -->\r\n");
      out.write("\t\t\t\t        <ol class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t\t            <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("\t\t\t\t            <li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("\t\t\t\t            <li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("\t\t\t\t        </ol>   \r\n");
      out.write("\t\t\t\t        <!-- Wrapper for carousel items -->\r\n");
      out.write("\t\t\t\t        <div class=\"carousel-inner\">\r\n");
      out.write("\t\t\t\t            <div class=\"item active\">\r\n");
      out.write("\t\t\t\t                <img src=\"resource/img/headers/2.png\"  alt=\"First Slide\">\r\n");
      out.write("\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t            <div class=\"item\">\r\n");
      out.write("\t\t\t\t                <img src=\"resource/img/headers/1.png\" alt=\"Second Slide\">\r\n");
      out.write("\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t            <div class=\"item\">\r\n");
      out.write("\t\t\t\t                <img src=\"resource/img/headers/3.png\" alt=\"Third Slide\">\r\n");
      out.write("\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t        <!-- Carousel controls -->\r\n");
      out.write("\t\t\t\t        <a class=\"carousel-control left\" href=\"#myCarousel\" data-slide=\"prev\">\r\n");
      out.write("\t\t\t\t            <span class=\"glyphicon glyphicon-chevron-left\"></span>\r\n");
      out.write("\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t        <a class=\"carousel-control right\" href=\"#myCarousel\" data-slide=\"next\">\r\n");
      out.write("\t\t\t\t            <span class=\"glyphicon glyphicon-chevron-right\"></span>\r\n");
      out.write("\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"mastfoot\">\r\n");
      out.write("            <div class=\"inner\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>                                \t\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
